In [2]:
import os
import io
import pandas as pd
import numpy as np
import glob
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

import datetime

#dask
import dask.dataframe as dd

import warnings
warnings.filterwarnings("ignore")

### Path

In [3]:
path = r"\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\\"

### PFMC

In [3]:
filenames = glob.glob(path + "\*pfmc*.csv")
print(filenames)

['\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\vul_pfmc_inf_monthly_2022_1.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\vul_pfmc_inf_monthly_2022_2.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\vul_pfmc_inf_monthly_2022_3.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\vul_pfmc_inf_monthly_2022_4.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\vul_pfmc_inf_monthly_2022_5.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\vul_pfmc_inf_monthly_2022_6.csv']

In [4]:
#list of all df
dfs = []
for f in filenames: 
    print(f)
    d = pd.read_csv(f, encoding="ISO-8859-1") 
    dfs.append(d) 
pfmc = pd.concat(dfs, ignore_index=True)
del dfs

\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\vul_pfmc_inf_monthly_2022_1.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\vul_pfmc_inf_monthly_2022_2.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\vul_pfmc_inf_monthly_2022_3.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\vul_pfmc_inf_monthly_2022_4.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\vul_pfmc_inf_monthly_2022_5.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\vul_pfmc_inf_monthly_2022_6.csv

In [5]:
pfmc['val_dt']= pfmc['val_dt'].astype('datetime64[ns]')
pfmc['pfmc_cur_month'] = pfmc['val_dt'].astype('datetime64[ns]').map(lambda x: x.strftime('%Y-%m'))
pfmc['pfmc_1m_ago'] =  ((pfmc['val_dt'] - pd.DateOffset(months=1)).dt.to_period("M")).astype(str)
# pfmc['pfmc_2m_ago'] =  ((pfmc['val_dt'] - pd.DateOffset(months=2)).dt.to_period("M")).astype(str)
# pfmc['pfmc_3m_ago'] =  ((pfmc['val_dt'] - pd.DateOffset(months=3)).dt.to_period("M")).astype(str)

In [53]:
pfmc.groupby('pfmc_cur_month')['agmt_pkge_id'].count()

pfmc_cur_month
2022-01    827272
2022-02    827819
2022-03    828187
2022-04    829537
2022-05    829921
2022-06    829977
Name: agmt_pkge_id, dtype: int64

In [6]:
pd.set_option('display.max_columns', None)
#pfmc.head()
pfmc[pfmc['agmt_pkge_id']=='990967950000']

,year,month,agmt_pkge_id,vul,ul,term,aos_status_code,val_inforce_cls,kind_code,sub_kind,conv_undrwrt_code,conv_type,spec_id,premium_basis,value_basis,series,band_code,lim_db_guar_per,admin_source_cd,tax_basis,non_forf_prv,div_option,liv_ben_sig,spec_und_code,pension_code,medical_issue_cd,prem_mode,debit_indicator,rptg_country,legal_ent,branch_of_business,pgls_product_code,closed_block_stat,int_loan_typ_cd,abbr_pay_typ_cd,opr_stat_cd,wsc_ind,iss_office_inforce,cur_office_inforce,iss_res_place_id,cur_res_place_id,iss_rmo,cur_rmo,iss_prem_mode,iss_offc_det_cd,crnt_offc_det_cd,fgn_ind,policy_part,cvrg_typ,prod_type,pln_id,gnrc_pln_id,ins_nature_cd,pln_desc,has_sps_ind,has_chld_ind,prem_pattern_cd,db_pattern_cd,liv_num,frst_scnd_dth_ind,mod_prem_num,lim_prem_sig_ind,term_cvrg_sig_ind,prem_pay_dur,prem_pay_age_num,cvrg_dur,cvrg_age_num,conv_sig_ind,conv_dur,conv_age_num,plan_type,qual_code,gi_ru_code,unisex_ind,ins_type_code,trad_intsens_code,conv_pct,lvl_prem_prd_num,enhnc_comp_ind,sngl_pay_ind,lvl_prem_prd_age,ecv_ind,lp_cntr_cd,lp_cntr_rsn_cd,lp_bill_cd,lp_bill_rsn_cd,lp_bnf_stat_cd,lp_bnf_rsn_cd,lp_canc_rsn_cd,nature,issue_age,extra_ratings,imp_rating,occ_rating,smoking_habit,pref_rating,select_rating,sex,undw_class,place_name,place_abbrev,acord_state_id,acord_ctry_id,base_face_amt,aip_face_amt,pua_face_amt,puar_face_amt,oyt_face_amt,layer_face_amt,designer_face_amt,rdr1_face_amt,rdr2_face_amt,rdr3_face_amt,rdr4_face_amt,rdr_other_face_amt,mpt_tot_act_val,mpt_3,mpt_4,mpt_1600,mpt_502,mpt_600,mpt_620,rtain_amt,ceded_amt,net_rsk_amt,units,trgt_7_pay,trgt_lmtd_pay,crnt_defcy_guar_fnd,tot_loan_prncpl,tot_loan_fnd_val,unpd_loan_int_due,annlzd_sch_prem,annlzd_bld_prem,modal_prem_sch,modal_prem_bld,grs_ropt_rdrprem_pd,base_pol_count,major_lob,lob_group,product_group,bar_feature,ny_state_specific,ttr_feature,issue_age_2nd,extra_ratings_2nd,imp_rating_2nd,occ_rating_2nd,smoking_habit_2nd,pref_rating_2nd,select_rating_2nd,gender_2nd,undw_class_2nd,base_pol_units,min_cntrct_fund,fund_lvl,holding_co_cd,policy_id,layer_units,rdr_units,layer_count,rdr_count,accum_actual_prem_paid,loan_rate,monthly_coi,prod_vers_desc,mktg_grp_desc,lnb_ind,rdr_term_ill_ind,base_fam_spo_ind,base_fam_child_ind,adb_pri_base_ind,adb_spo_base_ind,adb_layer_ind,aviation_xtra_base_ind,awp_base_ind,opai_ind,extc_ind,upb_ind,temp_xtra_base_ind,wp_base_ind,layer_ind,rdr_oyt_dsgn_ind,rdr_paidup_inc_dsgn_ind,oyt_ind,pua_base_pri_ind,pua_base_spo_ind,pua_rdr_ind,rdr_bar_ind,wp_rdr_child_ind,wp_rdr_pri_ind,wp_rdr_sps_ind,rdr_child_ind,rdr_pri_dec_term_ind,rdr_spo_dec_term_ind,rdr_pri_term_prot_ind,rdr_spo_term_prot_ind,rdr_est_prot_ind,rdr_trgt_term_ind,rdr_5rc_ind,rdr_other_ind,attained_age,attained_age_2nd,enhanced_val,conv_type_detail,policy_id_2nd,val_dt,last_up_dt,prod_issue_dt,issue_dt,reinstmt_dt,lapse_dt,xi_expiry_dt,paid_to_dt,run_dt,var_index_acct_rdr_ind,mpt_10,mpt_11,mpt_20881,run_dt_part,value_basis.1,premium_basis.1,prod_line_desc,prod_desc,prod_vers_desc.1,dtl_prod_desc,acord_prod_typ_cd,acord_prod_typ_desc,full_prod_desc,prod_grp,mktg_grp_desc.1,limra_lob_desc,start_dt,end_dt,pfmc_cur_month,pfmc_1m_ago
506883,2022,1,990967950000,YES,NaN,NaN,B,PP,01469,B,Y,T,269,1,14,E,X,0,A,0.0,1.0,12,Y,000,0.0,0,M,N,US,PRU,04 K P,44K,0,F,7.0,NaN,N,Q VI,QBNY,33,33,1,3.0,M,NaN,K,NaN,BASE,PRI,LIFE,VAL,VAL,PRI,VAL NS VAR,0,0,MODIFIED,VAR LIFE,1,1,1,0,0,999,999,999,999,0,0,0,VAI,NaN,NaN,N,L,I,0,999,NaN,N,999,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRI,31,0,0.0,0,N,Y,NaN,M,B,NEW YORK,NY,37.0,1.0,100000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28043.0,27022.0,1021.0,16088.0,0.0,28043.0,12046.50,0.0,0.0,0.0,100.0,0.0,0.0,0.0,26945.98,0.0,1482.03,966.72,979.56,80.56,81.63,0.0,1,Variable,Other Int-Sens,Variable Appreciable Life/VAL,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,0.0,P,99096795,0.0,0.0,0,0,0.0,0.055,0.0,NaN,Accumulation (cash),Y,N,N,N,Y,N,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,62,999,N,R,99096795,2022-01-31,2009-04-10,1990-05-04,1990-05-04,NaN,NaN,2014-01-19,2022-02-04,2022-01-31,NaN,12046.50,0.0,0.0,220131,16,2,Variable,VUL,NaN,VAL,4,Variable Universal Life,VAL,Other VUL,Accumulation (cash),Variable Universal Life,1997-09-30,NaN,2022-01,2021-12
1129979,2022,2,990967950000,YES,NaN,NaN,B,PP,01469,B,Y,T,269,1,14,E,X,0,A,0.0,1.0,12,Y,000,0.0,0,M,N,US,PRU,04 K P,44K,0,F,7.0,NaN,N,Q VI,QBNY,33,33,1,3.0,M,NaN,K,NaN,BASE,PRI,LIFE,VAL,VAL,PRI,VAL NS VAR,0,0,MODIFIED,VAR LIFE,1,1,1,0,0,999,999,999,999,0,0,0,VAI,NaN,NaN,N,L,I,0,999,NaN,N,999,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRI,31,0,0.0,0,N,Y,NaN,M,B,NEW YORK,NY,37.0,1.0,100000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28128.0,26986.0,1142.0,16088.0,0.0,28128.0,12140.78,0.0,0.0,0.0,100.0,0.0,0.0,0.0,26945.98,0.0,1482.03,966.72,979.56,80.56,81.63,0.0,1,Variable,Other Int-Sens,Variable Appreciable Life/VAL,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,0.0,P,99096795,0.0,0.0,0,0,0.0,0.055,0.0,NaN,Accumulation (cash),Y,N,N,N,Y,N,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,62,999,N,R,99096795,2022-02-28,2009-04-10,1990-05-04,1990-05-04,NaN,NaN,2014-01-19,2022-03-04,2022-02-28,NaN,12140.78,0.0,0.0,220228,16,2,Variable,VUL,NaN,VAL,4,Variable Universal Life,VAL,Other VUL,Accumulation (cash),Variable Universal Life,1997-09-30,NaN,2022-02,2022-01
2205096,2022,3,990967950000,YES,NaN,NaN,B,PP,01469,B,Y,T,269,1,14,E,X,0,A,0.0,1.0,12,Y,000,0.0,0,M,N,US,PRU,04 K P,44K,0,F,7.0,NaN,N,Q VI,QBNY,33,33,1,3.0,M,NaN,K,NaN,BASE,PRI,LIFE,VAL,VAL,PRI,VAL NS VAR,0,0,MODIFIED,VAR LIFE,1,1,1,0,0,999,999,999,999,0,0,0,VAI,NaN,NaN,N,L,I,0,999,NaN,N,999,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRI,31,0,0.0,0,N,Y,NaN,M,B,NEW YORK,NY,37.0,1.0,100000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28260.0,27006.0,1254.0,16088.0,0.0,28260.0,12283.05,0.0,0.0,0.0,100.0,0.0,0.0,0.0,26945.98,0.0,1482.03,966.72,979.56,80.56,81.63,0.0,1,Variable,Other Int-Sens,Variable Appreciable Life/VAL,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,0.0,P,99096795,0.0,0.0,0,0,0.0,0.055,0.0,NaN,Accumulation (cash),Y,N,N,N,Y,N,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,62,999,N,R,99096795,2022-03-31,2009-04-10,1990-05-04,1990-05-04,NaN,NaN,2014-01-19,2022-04-04,2022-04-01,NaN,12283.05,0.0,0.0,220401,16,2,Variable,VUL,NaN,VAL,4,Variable Universal Life,VAL,Other VUL,Accumulation (cash),Variable Universal Life,1997-09-30,NaN,2022-03,2022-02
4365208,2022,6,990967950000,YES,NaN,NaN,B,PP,01469,B,Y,T,269,1,14,E,X,0,A,0.0,1.0,12,Y,000,0.0,0,M,N,US,PRU,04 K P,44K,0,F,7.0,NaN,N,Q VI,QBNY,33,33,1,3.0,M,NaN,K,NaN,BASE,PRI,LIFE,VAL,VAL,PRI,VAL NS VAR,0,0,MODIFIED,VAR LIFE,1,1,1,0,0,999,999,999,999,0,0,0,VAI,NaN,NaN,N,L,I,0,999,NaN,N,999,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRI,31,0,0.0,0,N,Y,NaN,M,B,NEW YORK,NY,37.0,1.0,100000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28627.0,27550.0,1077.0,15967.0,0.0,28627.0,12707.80,0.0,0.0,0.0,100.0,0.0,0.0,0.0,27541.13,0.0,1517.40,966.72,979.56,80.56,81.63,0.0,1,Variable,Other Int-Sens,Variable Appreciable Life/VAL,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,0.0,P,99096795,0.0,0.0,0,0,0.0,0.055,0.0,NaN,Accumulation (cash),Y,N,N,N,Y,N,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,63,999,N,R,99096795,2022-06-30,2022-06-17,1990-05-04,1990-05-04,NaN,NaN,2014-01-19,2022-07-04,2022-07-01,NaN,12707.80,0.0,0.0,220701,16,2,Variable,VUL,NaN,VAL,4,Variable Universal Life,VAL,Other VUL,Accumulation (cash),Variable Universal Life,1997-09-30,NaN,2022-06,2022-05

### Events_Monthly

In [4]:
filenames = glob.glob(path + "\*events_monthly*.csv")
print(filenames)

['\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\events_monthly_2022_4.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\events_monthly_2022_5.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\events_monthly_2022_6.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\events_monthly_2022_7.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\events_monthly_2022_8.csv', '\\\\VNCRP1002\\\\ud03$\\\\X266754\\\\My Documents\\\\Lapse\\\\Data\\events_monthly_2022_9.csv']

In [5]:
#list of all df
dfs = []
for f in filenames: 
    print(f)
    d = pd.read_csv(f, encoding="ISO-8859-1") 
    dfs.append(d) 
events = pd.concat(dfs, ignore_index=True)
del dfs

\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\events_monthly_2022_4.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\events_monthly_2022_5.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\events_monthly_2022_6.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\events_monthly_2022_7.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\events_monthly_2022_8.csv
\\VNCRP1002\\ud03$\\X266754\\My Documents\\Lapse\\Data\events_monthly_2022_9.csv

In [7]:
events.dtypes

year                int64
month               int64
agmt_pkge_id       object
aos_status_code    object
val_inforce_cls    object
                    ...
xi_expiry_dt       object
paid_to_dt         object
gnrc_dt            object
prcs_dt            object
evnt_dt            object
Length: 119, dtype: object

In [56]:
#import dateutil.relativedelta #evnt_dt or prcs_dt?
events['prcs_dt']= events['prcs_dt'].astype('datetime64[ns]')
events['evnt_cur_month'] = events['prcs_dt'].map(lambda x: x.strftime('%Y-%m'))
events['evnt_1_month_ago'] =  ((events['prcs_dt'] - pd.DateOffset(months=1)).dt.to_period("M")).astype(str)
events['evnt_2_month_ago'] =  ((events['prcs_dt'] - pd.DateOffset(months=2)).dt.to_period("M")).astype(str)
events['evnt_3_month_ago'] =  ((events['prcs_dt'] - pd.DateOffset(months=3)).dt.to_period("M")).astype(str)

In [58]:
# indicator
events['lapse_ind'] = (np.where(events['evnt_desc'].str.contains('Lapse', na=False),1, 0)).astype(int)
events['surrender_ind'] = (np.where(events['evnt_desc'].str.contains('Surrender',na=False),1, 0)).astype(int)
events['reinstate_ind'] = (np.where(events['evnt_desc'].str.contains('True Reinstatement',na=False),1, 0)).astype(int)

In [10]:
events[events['reinstate_ind']==1].head()

,year,month,agmt_pkge_id,aos_status_code,val_inforce_cls,sub_kind,conv_undrwrt_code,conv_type,premium_basis,value_basis,...,gnrc_dt,prcs_dt,evnt_dt,evnt_cur_month,evnt_1_month_ago,evnt_2_month_ago,evnt_3_month_ago,lapse_ind,surrender_ind,reinstate_ind
12,2022,4,469815270000,B,PP,NaN,NaN,NaN,2,11,...,NaN,2022-04-29,2022-04-29,2022-04,2022-03,2022-02,2022-01,0,0,1
26,2022,4,L96556870000,A,PP,NaN,NaN,NaN,1,29,...,NaN,2022-04-29,2022-04-29,2022-04,2022-03,2022-02,2022-01,0,0,1
29,2022,4,833085180000,E,RPUL,NaN,NaN,NaN,2,9,...,NaN,2022-04-29,2022-04-29,2022-04,2022-03,2022-02,2022-01,0,0,1
44,2022,4,831743530000,B,PP,NaN,NaN,NaN,2,9,...,NaN,2022-04-29,2022-04-29,2022-04,2022-03,2022-02,2022-01,0,0,1
68,2022,4,L81713820000,A,PP,NaN,NaN,NaN,1,23,...,NaN,2022-04-29,2022-04-29,2022-04,2022-03,2022-02,2022-01,0,0,1

In [59]:
events.groupby('evnt_cur_month')['agmt_pkge_id'].count()

evnt_cur_month
2018-11        1
2018-12        1
2021-05        9
2021-06       16
2021-07       16
2021-08       36
2021-09       42
2021-10       31
2021-11       50
2021-12       41
2022-01       40
2022-02       33
2022-03       53
2022-04    12090
2022-05    10016
2022-06    14888
2022-07    14315
2022-08    15991
2022-09    14907
2022-10     5919
Name: agmt_pkge_id, dtype: int64

In [70]:
sample = events[(events['evnt_cur_month']=='2022-08')&(events['surrender_ind']==1)&((events['lob_group']=='VUL'))]
sample.groupby(['evnt_cur_month', 'evnt_desc'])['lob_group'].count()
sample.head()

,year,month,agmt_pkge_id,aos_status_code,val_inforce_cls,sub_kind,conv_undrwrt_code,conv_type,premium_basis,value_basis,admin_source_cd,prem_mode,debit_indicator,rptg_country,legal_ent,pgls_product_code,closed_block_stat,wsc_ind,iss_office_inforce,cur_res_place_id,cur_rmo,crnt_offc_det_cd,fgn_ind,pln_id,gnrc_pln_id,pln_desc,prem_pattern_cd,db_pattern_cd,prem_pay_age_num,cvrg_age_num,conv_age_num,plan_type,ins_type_code,trad_intsens_code,lvl_prem_prd_num,lp_cntr_cd,lp_cntr_rsn_cd,lp_bnf_stat_cd,lp_bnf_rsn_cd,lp_canc_rsn_cd,issue_age,extra_ratings,imp_rating,occ_rating,smoking_habit,pref_rating,select_rating,sex,undw_class,place_name,place_abbrev,acord_state_id,acord_ctry_id,units,base_pol_count,major_lob,lob_group,product_group,issue_age_2nd,extra_ratings_2nd,imp_rating_2nd,occ_rating_2nd,smoking_habit_2nd,pref_rating_2nd,select_rating_2nd,gender_2nd,undw_class_2nd,base_face_amt,aip_face_amt,pua_face_amt,puar_face_amt,oyt_face_amt,layer_face_amt,designer_face_amt,rdr1_face_amt,rdr2_face_amt,rdr3_face_amt,rdr4_face_amt,rdr_other_face_amt,loan_prin,base_pol_units,fund_lvl,holding_co_cd,layer_units,rdr_units,layer_count,rdr_count,prod_vers_desc,mktg_grp_desc,lnb_ind,rdr_term_ill_ind,rdr_bar_ind,attained_age,attained_age_2nd,conv_type_detail,policy_id_2nd,infrc_chng_cd,evnt_typ_cd,evnt_dur,evnt_catg_combo_cd,evnt_catg_cd,incr_decr_cd,evnt_desc,prev_val_infrc_grp,crnt_val_infrc_grp,undw_ind,delta_cnt,delta_amt,prem_delta_amt,val_dt,prod_issue_dt,issue_dt,reinstmt_dt,lapse_dt,xi_expiry_dt,paid_to_dt,gnrc_dt,prcs_dt,evnt_dt,evnt_cur_month,evnt_prev_month,lapse_ind,surrender_ind
59298,2022,8,V30159800000,S,CANC,A,NaN,1,1,16,V,A,N,US,AZ,002,0,N,MIL4,50,4,NaN,NaN,VUL,VUL,VUL LEV DB,LEVEL,VAR LIFE,999,999,0,VUL,L,I,999,NaN,NaN,NaN,NaN,NaN,30,0,0.0,0.0,N,Y,Y,M,D,WISCONSIN,WI,58.0,1.0,100.0,1,Variable,VUL,Variable Universal Life/VUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,P,0.0,0.0,0,0,NaN,Accumulation (cash),Y,N,N,52,999,NaN,V3015980,4,15,23,1,1,D,Surrender,PP,CANC,N,-1,-100000.0,0.0,2022-10-05,2000-04-10,2000-04-10,NaN,NaN,NaN,2022-09-10,NaN,2022-08-31,2022-08-31,2022-08,2022-07,0,1
59300,2022,8,VL81307640000,2,CANC,A,NaN,1,9,99,K,A,N,US,ILA,051,0,N,A,17,U,NaN,NaN,VUL LEG,VUL,HARTFORD LEADERS VUL LEGACY,UNKNOWN,UNK,999,999,999,PVL,L,I,999,NaN,NaN,NaN,NaN,NaN,26,0,0.0,0.0,N,NaN,NaN,F,3,KANSAS,KS,20.0,1.0,105.0,1,Variable,VUL,Other Variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,105.0,0.0,H,0.0,0.0,0,0,NaN,Other,N,N,N,37,999,NaN,VL8130764,4,15,12,1,1,D,Surrender,PP,CANC,N,-1,-105000.0,0.0,2022-10-05,2011-06-17,2011-06-17,NaN,NaN,NaN,2023-06-17,NaN,2022-08-31,2022-08-31,2022-08,2022-07,0,1
59303,2022,8,V12291970000,S,CANC,B,N,1,4,18,V,A,N,US,AZ,002,0,N,PT1X,10,4,NaN,NaN,VUL II,VUL,VUL2 GLP Var DB,LEVEL,VAR LIFE,999,999,0,VU2,L,I,999,NaN,NaN,NaN,NaN,NaN,39,0,0.0,0.0,N,NaN,NaN,F,1,NEW JERSEY,NJ,35.0,1.0,1300.0,1,Variable,VUL,Custom Premier/VUL II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1300000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1300.0,0.0,P,0.0,0.0,0,0,Pre Apr 2008,Accumulation (cash),Y,N,N,54,999,R,V1229197,4,15,16,1,1,D,Surrender,PP,CANC,N,-1,-1300000.0,0.0,2022-10-05,2007-04-09,2007-04-09,NaN,NaN,NaN,2022-09-09,NaN,2022-08-31,2022-08-31,2022-08,2022-07,0,1
59365,2022,8,V80010760000,S,CANC,B,Y,1,1,16,V,A,N,US,AZ,002,0,N,LANC,39,2,NaN,NaN,VUL,VUL,VUL VAR DB,LEVEL,VAR LIFE,999,999,0,VUL,L,I,999,NaN,NaN,NaN,NaN,NaN,34,0,0.0,0.0,N,Y,Y,M,D,PENNSYLVANIA,PA,45.0,1.0,250.0,1,Variable,VUL,Variable Universal Life/VUL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100000.0,0.0,100.0,0.0,P,0.0,150.0,0,3,NaN,Accumulation (cash),Y,N,N,57,999,R,V8001076,4,15,24,1,1,D,Surrender,PP,CANC,N,-1,-100000.0,0.0,2022-10-05,1999-04-27,1999-04-27,NaN,NaN,NaN,2022-09-27,NaN,2022-08-31,2022-08-31,2022-08,2022-07,0,1
59368,2022,8,V20395550000,S,CANC,B,NaN,1,1,20,V,A,N,US,AZ,002,0,N,SEAX,12,4,E,NaN,VUL II,VUL,VUL2 GLP Var DB,LEVEL,VAR LIFE,999,999,0,VU2,L,I,999,NaN,NaN,NaN,NaN,NaN,31,0,0.0,0.0,N,NaN,NaN,M,1,HAWAII,HI,15.0,1.0,250.0,1,Variable,VUL,Custom Premier/VUL II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,0.0,P,0.0,0.0,0,0,Apr 2008,Accumulation (cash),Y,N,N,44,999,NaN,V2039555,4,15,14,1,1,D,Surrender,PP,CANC,N,-1,-250000.0,0.0,2022-10-05,2008-11-06,2008-11-06,NaN,NaN,NaN,2022-09-06,NaN,2022-08-31,2022-08-31,2022-08,2022-07,0,1

In [32]:
# surrender in Aug - 2022
pd.set_option('display.max_columns', None)
events[events['agmt_pkge_id']=='R41308960000']

,year,month,agmt_pkge_id,aos_status_code,val_inforce_cls,sub_kind,conv_undrwrt_code,conv_type,premium_basis,value_basis,admin_source_cd,prem_mode,debit_indicator,rptg_country,legal_ent,pgls_product_code,closed_block_stat,wsc_ind,iss_office_inforce,cur_res_place_id,cur_rmo,crnt_offc_det_cd,fgn_ind,pln_id,gnrc_pln_id,pln_desc,prem_pattern_cd,db_pattern_cd,prem_pay_age_num,cvrg_age_num,conv_age_num,plan_type,ins_type_code,trad_intsens_code,lvl_prem_prd_num,lp_cntr_cd,lp_cntr_rsn_cd,lp_bnf_stat_cd,lp_bnf_rsn_cd,lp_canc_rsn_cd,issue_age,extra_ratings,imp_rating,occ_rating,smoking_habit,pref_rating,select_rating,sex,undw_class,place_name,place_abbrev,acord_state_id,acord_ctry_id,units,base_pol_count,major_lob,lob_group,product_group,issue_age_2nd,extra_ratings_2nd,imp_rating_2nd,occ_rating_2nd,smoking_habit_2nd,pref_rating_2nd,select_rating_2nd,gender_2nd,undw_class_2nd,base_face_amt,aip_face_amt,pua_face_amt,puar_face_amt,oyt_face_amt,layer_face_amt,designer_face_amt,rdr1_face_amt,rdr2_face_amt,rdr3_face_amt,rdr4_face_amt,rdr_other_face_amt,loan_prin,base_pol_units,fund_lvl,holding_co_cd,layer_units,rdr_units,layer_count,rdr_count,prod_vers_desc,mktg_grp_desc,lnb_ind,rdr_term_ill_ind,rdr_bar_ind,attained_age,attained_age_2nd,conv_type_detail,policy_id_2nd,infrc_chng_cd,evnt_typ_cd,evnt_dur,evnt_catg_combo_cd,evnt_catg_cd,incr_decr_cd,evnt_desc,prev_val_infrc_grp,crnt_val_infrc_grp,undw_ind,delta_cnt,delta_amt,prem_delta_amt,val_dt,prod_issue_dt,issue_dt,reinstmt_dt,lapse_dt,xi_expiry_dt,paid_to_dt,gnrc_dt,prcs_dt,evnt_dt,evnt_cur_month,evnt_1_month_ago,evnt_2_month_ago,evnt_3_month_ago,lapse_ind,surrender_ind,reinstate_ind
49951,2022,7,R41308960000,B,PP,B,NaN,NaN,1,13,A,M,N,US,AZ,44K,0,N,ELGN,14,4,L,NaN,VAL,VAL,VAL-VARIABLE DB,MODIFIED,VAR LIFE,999,999,0,VAI,L,I,999,NaN,NaN,NaN,NaN,NaN,46,0,0.0,0.0,N,Y,NaN,F,B,ILLINOIS,IL,17.0,1.0,50.0,1,Variable,Other Int-Sens,Variable Appreciable Life/VAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0,P,0.0,0.0,0,0,NaN,Accumulation (cash),Y,N,N,80,999,NaN,R4130896,59,5,35,1,1,I,True Reinstatement,XI,PP,N,0,0.0,0.0,2022-11-02,1987-11-12,1987-11-12,NaN,NaN,2023-12-31,2022-09-12,NaN,2022-07-29,2022-07-29,2022-07,2022-06,2022-05,2022-04,0,0,1

In [60]:
events['evnt_desc'].unique()

array(['Surrender', 'Lapse With No Value', 'True Reinstatement',
       'Reinstatement and Lapse to XI', 'Lapse Pending'], dtype=object)

### Join PFMC Inf and Events to get Lapse policiies  (3month ahead)

In [61]:
# Merge pfmv and events
df = pfmc.merge(events[['agmt_pkge_id','evnt_desc','lapse_ind', 'surrender_ind', 'reinstate_ind',
                        'evnt_1_month_ago', 'evnt_2_month_ago', 'evnt_3_month_ago', 
                        'evnt_cur_month']], 
              how='left', 
              left_on=['agmt_pkge_id', 'pfmc_cur_month'], 
              right_on=['agmt_pkge_id', 'evnt_3_month_ago'], 
              suffixes=('', '_remove'))

df.drop([i for i in df.columns if 'remove' in i],axis=1, inplace=True)

In [62]:
df.shape

(4972713, 246)

In [63]:
del pfmc, events

In [11]:
df['evnt_desc'].unique()

array([nan, 'Surrender', 'Lapse With No Value', 'True Reinstatement'],
      dtype=object)

In [51]:
# lapse and surrender indicator
#df['lapse_ind'] = (np.where(df['evnt_desc'].str.contains('Lapse', na=False),1, 0)).astype(int)
#df['surrender_ind'] = (np.where(df['evnt_desc'].str.contains('Surrender'),1, 0)).astype(int)

In [78]:
df[df['lapse_ind']==1]['year'].count()

1332

In [2]:
sample = df[df['agmt_pkge_id']=='V26931570000']
#sample.to_csv("sample_lapse.csv")
sample

NameError: name 'df' is not defined

In [64]:
## Lagged lapse indicators
df['lapse_ind']= df['lapse_ind'].fillna(0)
df['lapse_ind_lag1'] = df.groupby('agmt_pkge_id')['lapse_ind'].shift(1)
df['lapse_ind_lag1']=df['lapse_ind_lag1'].fillna(0)

df['lapse_ind_lag2'] = df.groupby('agmt_pkge_id')['lapse_ind'].shift(2)
df['lapse_ind_lag2']=df['lapse_ind_lag2'].fillna(0)

df['lapse_ind_lag3'] = df.groupby('agmt_pkge_id')['lapse_ind'].shift(3)
df['lapse_ind_lag3']=df['lapse_ind_lag3'].fillna(0)

In [65]:
df['reinstate_ind']= df['reinstate_ind'].fillna(0)
df['reinstate_ind_lag1'] = df.groupby('agmt_pkge_id')['reinstate_ind'].shift(1)
df['reinstate_ind_lag1']=df['reinstate_ind_lag1'].fillna(0)

df['reinstate_ind_lag2'] = df.groupby('agmt_pkge_id')['reinstate_ind'].shift(2)
df['reinstate_ind_lag2']=df['reinstate_ind_lag2'].fillna(0)

df['reinstate_ind_lag3'] = df.groupby('agmt_pkge_id')['reinstate_ind'].shift(3)
df['reinstate_ind_lag3']=df['reinstate_ind_lag3'].fillna(0)

In [66]:
df['surrender_ind']= df['surrender_ind'].fillna(0)
df['surrender_ind_lag1'] = df.groupby('agmt_pkge_id')['surrender_ind'].shift(1)
df['surrender_ind_lag1']=df['surrender_ind_lag1'].fillna(0)

df['surrender_ind_lag2'] = df.groupby('agmt_pkge_id')['surrender_ind'].shift(2)
df['surrender_ind_lag2']=df['surrender_ind_lag2'].fillna(0)

df['surrender_ind_lag3'] = df.groupby('agmt_pkge_id')['surrender_ind'].shift(3)
df['surrender_ind_lag3']=df['surrender_ind_lag3'].fillna(0)

In [67]:
df['cur_status']= np.where(df['lapse_ind']==1, 'lapse', 
                           (np.where(df['surrender_ind']==1, 'surrender', 
                             (np.where(df['reinstate_ind']==1, 'reinstated',  "current")))))

In [68]:
df['prior_1mo_status']= np.where(df['lapse_ind_lag1']==1, 'lapse', 
                           (np.where(df['surrender_ind_lag1']==1, 'surrender', 
                           (np.where(df['reinstate_ind_lag1']==1, 'reinstated',  "current")))))

In [69]:
df['prior_2mo_status']= np.where(df['lapse_ind_lag2']==1, 'lapse', 
                           (np.where(df['surrender_ind_lag2']==1, 'surrender', 
                           (np.where(df['reinstate_ind_lag2']==1, 'reinstated',  "current")))))

In [70]:
df['prior_3mo_status']= np.where(df['lapse_ind_lag3']==1, 'lapse', 
                           (np.where(df['surrender_ind_lag3']==1, 'surrender', 
                           (np.where(df['reinstate_ind_lag3']==1, 'reinstated',  "current")))))

In [45]:
dgroup = df.groupby(["pfmc_cur_month", "lapse_ind"], as_index=True)['lapse_ind'].count()
dgroup

cur_month  lapse_ind
2022-04    0.0          829291
           1.0             246
2022-05    0.0          829646
           1.0             275
2022-06    0.0          829974
           1.0               3
2022-07    0.0          830654
2022-08    0.0          830512
Name: lapse_ind, dtype: int64

In [46]:
dgroup = df.groupby(["pfmc_cur_month", "surrender_ind"], as_index=True)['agmt_pkge_id'].count()
dgroup

cur_month  surrender_ind
2022-04    0.0              828182
           1.0                1355
2022-05    0.0              828325
           1.0                1596
2022-06    0.0              829977
2022-07    0.0              830654
2022-08    0.0              830512
Name: agmt_pkge_id, dtype: int64

In [42]:
pd.set_option('display.max_columns', None)
df[df['prior_1mo_status']=='surrender']['policy_id'].count()

2951

### Transition Matrix

In [71]:
sample = df[df['pfmc_cur_month']=='2022-05']
tmatrix = pd.crosstab(index=sample['prior_1mo_status'], columns=[sample['cur_status']]).reset_index()
tmatrix

cur_status prior_1mo_status  current  lapse  reinstated  surrender
0                   current   826396    275          19       1596
1                     lapse      225      0          21          0
2                reinstated       34      0           0          0
3                 surrender     1354      0           1          0

In [73]:
sample = df[df['pfmc_cur_month']=='2022-05']
tmatrix = pd.crosstab(index=sample['prior_3mo_status'], columns=[sample['cur_status']]).reset_index()
tmatrix

cur_status prior_3mo_status  current  lapse  reinstated  surrender
0                   current   827982    273          40       1596
1                     lapse        7      0           0          0
2                reinstated       17      2           1          0
3                 surrender        3      0           0          0

In [86]:
sample = df[df['pfmc_cur_month']=='2022-05']
tmatrix = pd.crosstab(index=sample['prior_3mo_status'], columns=[sample['cur_status']],normalize='index').round(4)*100
tmatrix

cur_status        current  lapse  reinstated  surrender
prior_3mo_status
current             99.77   0.03         0.0       0.19
lapse              100.00   0.00         0.0       0.00
reinstated          85.00  10.00         5.0       0.00
surrender          100.00   0.00         0.0       0.00

In [72]:
pd.crosstab(index=sample['prior_1mo_status'], columns=[sample['cur_status']],normalize='index').round(4)*100

cur_status        current  lapse  reinstated  surrender
prior_1mo_status
current             99.77   0.03        0.00       0.19
lapse               91.46   0.00        8.54       0.00
reinstated         100.00   0.00        0.00       0.00
surrender           99.93   0.00        0.07       0.00

In [89]:
pd.crosstab(index=sample['prior_3mo_status'], columns=[sample['cur_status']])

cur_status        current  lapse  reinstated  surrender
prior_3mo_status
current            827982    273          40       1596
lapse                   7      0           0          0
reinstated             17      2           1          0
surrender               3      0           0          0

In [87]:
pd.crosstab(index=sample['prior_3mo_status'], columns=[sample['cur_status']],normalize='index').round(4)*100

cur_status        current  lapse  reinstated  surrender
prior_3mo_status
current             99.77   0.03         0.0       0.19
lapse              100.00   0.00         0.0       0.00
reinstated          85.00  10.00         5.0       0.00
surrender          100.00   0.00         0.0       0.00

In [90]:
df.drop('iss_rmo', axis=1, inplace=True)
df.to_parquet('pfmc_jan_june.parquet')

### Feature Engineering

In [23]:
# def fn_change(col):
#     col_lag = col + '_lag1'
#     col_change = col + '_mom_change'
#     df[col_lag] = df.groupby(['agmt_pkge_id'])[col].shift(1)
#     df[col_change] = df[col] - df[col_lag]
#     df[col_change]= df[col_change].fillna(method='bfill') 
#     df.drop(col_lag, axis=1, inplace=True) 
    
#     #forward fill non-zero
#     df[col_change] = df.groupby('agmt_pkge_id')[col_change].apply(lambda x: x.replace(to_replace=0, method='ffill'))
#     #df.update(df.groupby('agmt_pkge_id')[col_change].ffill().fillna(0))